-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

SELECT * from samples.nyctaxi.trips

-- COMMAND ----------

use catalog pipeline

-- COMMAND ----------

select s.customer_id, c.customer_email, c.customer_city, round(sum(total_amount)) as total_sales
from silver.sales_cleaned s
join gold.customers_active c
using(customer_id)
group by customer_id,customer_email,customer_city
order by total_sales desc
